######################################################################
# Automatically generated by qmake (3.1) Tue Feb 11 10:47:08 2025
######################################################################

TEMPLATE = app

QT += core gui bluetooth

CONFIG += c++17

SOURCES += main.cpp

HEADERS += QtBtButtons.h
FORMS += QtBtButtons.ui
